### PR TITLE
International region selection

### PR DESCRIPTION
**Pull request by raphaelr**
Replaces the japanese regions with the ones from the US + European releases. The region list can be modified, reduced, or expanded as necessary.

I tested some random region+date pairs, and the results I got were identical to the ones from Boktai 2. The script.sjs changes and the reigon_select.ips patch depend on each other; either apply both of them, or none of them.

work 2024-09-06 09 04 37

To do:
* Daylight savings time selection
* Fixing the page names (these are graphics instead of strings, and now we have more pages than graphics, leading to screens like this):

work 2024-09-06 09 01 26

### CODE REVIEW

**Comment by raphaelr** [comment]
Changed page names from graphics to plain text, as discussed. Due to a happy coincidence, the "brown text on yellow background" palette is loaded during this menu, so we can use that for displaying the page names - and we don't need to implement transparent text or anything like that:

region_select-0

**Comment by LanHikariDS** [comment]
Honestly, I wouldn't even consider the DST toggle a todo on this PR, but it's up to you how you want to handle it. DST is still implemented in the base game, I _believe_ 0x0F in the save file triggers it, my main save has it activated.

**Comment by raphaelr** [comment]
Yeah, DST won't be in this PR. I'll try to add it to the date/time menu later.

**Comment by LanHikariDS** [comment]
Anyways, am I correct in assuming this PR is ostensibly complete? I'll do a pass through this and double-check for any bugs, and merge it if we're all good.

**Pull request merged**
